#!/usr/bin/env python3
"""
Apply auto-extracted anchor candidates to addresses.yaml.

Workflow (run after ghidra_anchor_extractor.py has emitted JSON):

    python3 tools/addresses/apply_auto_anchors.py
    python3 tools/addresses/apply_auto_anchors.py --dry-run
    python3 tools/addresses/apply_auto_anchors.py --min-confidence high

For each function_pointer entry in addresses.yaml:
  - Look up its symbol in anchor_candidates.json
  - Run all candidates through anchor_scorer.pick_best()
  - If the winning candidate is at or above --min-confidence, write
    anchor_kind / anchor_value / anchor_score into the entry and update
    confidence (unknown -> high|medium|low|none).

The schema stays flat (anchor_kind, anchor_value, anchor_score) rather
than nested, because read_entries in codegen.py is a deliberately
minimal YAML parser that does not handle nested objects. The Ghidra
script + this driver + the scorer agree on the flat layout.

Idempotent: entries with an existing anchor_value are skipped unless
--force is passed.

Exit codes:
  0  ok
  1  driver-level error
  2  bad arguments / missing inputs
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from codegen import read_entries  # noqa: E402
from anchor_scorer import pick_best  # noqa: E402


CONFIDENCE_RANK = {'none': 0, 'low': 1, 'medium': 2, 'high': 3}


_YAML_RESERVED = set(':#*&!|>%@`')


def yaml_scalar(s):
    """Quote when YAML special chars would otherwise change the meaning."""
    if s is None or s == '':
        return '""'
    s = str(s)
    if (any(c in _YAML_RESERVED for c in s)
            or s.startswith('-') or s.startswith('?')
            or s.startswith('[') or s.startswith('{')
            or s.startswith('<')
            or s != s.strip()):
        escaped = s.replace('\\', '\\\\').replace('"', '\\"')
        return '"%s"' % escaped
    return s


def emit_yaml(entries, out_path):
    lines = [
        '# Auto-generated by tools/addresses/bootstrap_extractor.py and',
        '# updated by tools/addresses/apply_auto_anchors.py.',
        '# DO NOT edit this file by hand for routine updates -- rerun the tools.',
        '#',
        '# Schema (v2):',
        '#   name           short identifier (variable name from source)',
        '#   symbol         fully-qualified name (namespace::name)',
        '#   signature      typedef signature, or "<unknown>"',
        '#   category       subsystem (camera, object, scene, ...)',
        '#   original_addr  address as seen in the original SWG client (0xXXXXXXXX)',
        '#   bg_addr        address in Bellum Gero (when known); omitted otherwise',
        '#   source         file:line where the binding lives',
        '#   kind           function_pointer | nop_patch | data_read | data_write | address_constant',
        '#   confidence     unknown | none | low | medium | high',
        '#   anchor_kind    string_xref | import_pattern | byte_signature | vtable_slot',
        '#   anchor_value   the anchor data (e.g., the referenced string)',
        '#   anchor_score   numeric quality score (0..100, higher = better)',
        '#   nop_bytes      (nop_patch only) number of NOP bytes written',
        '',
    ]
    fields_order = (
        'name', 'symbol', 'signature', 'category', 'original_addr', 'bg_addr',
        'source', 'kind', 'confidence',
        'anchor_kind', 'anchor_value', 'anchor_score',
        'nop_bytes',
    )
    for e in entries:
        first = True
        for f in fields_order:
            if f not in e:
                continue
            value = e[f]
            if value == '' or value is None:
                continue
            prefix = '- ' if first else '  '
            first = False
            if f in ('original_addr', 'bg_addr'):
                lines.append('%s%s: %s' % (prefix, f, value))
            elif f in ('nop_bytes', 'anchor_score'):
                lines.append('%s%s: %s' % (prefix, f, value))
            elif f in ('kind', 'confidence', 'anchor_kind'):
                lines.append('%s%s: %s' % (prefix, f, value))
            else:
                lines.append('%s%s: %s' % (prefix, f, yaml_scalar(value)))
        lines.append('')
    out_path.write_text('\n'.join(lines), encoding='utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__.strip().split('\n')[0])
    parser.add_argument('--yaml', type=Path,
                        default=Path('tools/addresses/addresses.yaml'))
    parser.add_argument('--candidates', type=Path,
                        default=Path('tools/addresses/anchor_candidates.json'))
    parser.add_argument('--output', type=Path, default=None,
                        help='Output YAML path (default: in-place edit of --yaml).')
    parser.add_argument('--dry-run', action='store_true',
                        help='Report what would change without writing files.')
    parser.add_argument('--min-confidence',
                        choices=('none', 'low', 'medium', 'high'),
                        default='low',
                        help='Reject any winning anchor below this level.')
    parser.add_argument('--force', action='store_true',
                        help='Overwrite existing anchors (default: leave alone).')
    args = parser.parse_args()

    if not args.yaml.is_file():
        print('ERROR: YAML not found: %s' % args.yaml, file=sys.stderr)
        return 2
    if not args.candidates.is_file():
        print('ERROR: candidates JSON not found: %s' % args.candidates, file=sys.stderr)
        print('       Run the Ghidra extractor first.', file=sys.stderr)
        return 2

    entries = read_entries(args.yaml)
    with args.candidates.open('r', encoding='utf-8') as fh:
        candidates_data = json.load(fh)

    min_rank = CONFIDENCE_RANK[args.min_confidence]
    counts = {
        'updated': 0,
        'skipped_no_data': 0,
        'skipped_error': 0,
        'skipped_low_conf': 0,
        'skipped_already': 0,
        'skipped_no_candidates': 0,
    }
    by_confidence = {'high': 0, 'medium': 0, 'low': 0, 'none': 0}

    for entry in entries:
        if entry.get('kind') != 'function_pointer':
            continue
        sym = entry['symbol']
        if sym not in candidates_data:
            counts['skipped_no_data'] += 1
            continue
        data = candidates_data[sym]
        if 'error' in data:
            counts['skipped_error'] += 1
            continue
        existing = entry.get('anchor_value', '').strip()
        if existing and not args.force:
            counts['skipped_already'] += 1
            continue
        candidates = data.get('candidates', [])
        if not candidates:
            counts['skipped_no_candidates'] += 1
            continue

        best = pick_best(candidates)
        if best is None:
            counts['skipped_no_candidates'] += 1
            continue
        conf = best['result']['confidence']
        if CONFIDENCE_RANK[conf] < min_rank:
            counts['skipped_low_conf'] += 1
            by_confidence[conf] += 1
            continue

        entry['anchor_kind'] = best['candidate']['kind']
        entry['anchor_value'] = best['candidate']['value']
        entry['anchor_score'] = best['result']['score']
        entry['confidence'] = conf
        counts['updated'] += 1
        by_confidence[conf] += 1

    out_path = args.output or args.yaml
    if not args.dry_run:
        emit_yaml(entries, out_path)

    print('Updated:              %d' % counts['updated'])
    print('  high confidence:    %d' % by_confidence['high'])
    print('  medium confidence:  %d' % by_confidence['medium'])
    print('  low confidence:     %d' % by_confidence['low'])
    print('Skipped:')
    print('  no Ghidra data:     %d' % counts['skipped_no_data'])
    print('  Ghidra error:       %d' % counts['skipped_error'])
    print('  already anchored:   %d' % counts['skipped_already'])
    print('  no candidates:      %d' % counts['skipped_no_candidates'])
    print('  below threshold:    %d  (min-confidence=%s)'
          % (counts['skipped_low_conf'], args.min_confidence))
    if args.dry_run:
        print('(dry-run: no files written)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
