#!/usr/bin/env python3
"""
Codegen step of the Utinni address-table pipeline.

Reads tools/addresses/addresses.yaml and emits a C++ header containing
`constexpr` address constants nested in namespaces that mirror each
entry's `symbol` field.

Only entries of kind `function_pointer` or `address_constant` are
emitted as named constants -- `nop_patch`, `data_read`, and `data_write`
addresses remain inline at their call sites for now (they have synthetic
names that wouldn't make the source clearer; the validator still tracks
them via the YAML).

Address selection: uses `bg_addr` if present and non-empty, otherwise
`original_addr`. Pass --target=original to force original_addr always.

Usage:
    python3 tools/addresses/codegen.py
    python3 tools/addresses/codegen.py --input tools/addresses/addresses.yaml \
                                       --output UtinniCore/generated/addresses_generated.h \
                                       --target auto
"""

import argparse
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


# ----- minimal YAML reader for our specific schema -----

_QUOTED = re.compile(r'^"((?:[^"\\]|\\.)*)"$')


def _unquote(v: str) -> str:
    m = _QUOTED.match(v)
    if m:
        return m.group(1).replace('\\"', '"').replace('\\\\', '\\')
    return v


def read_entries(path: Path) -> list:
    entries = []
    current = None
    for lineno, raw in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        line = raw.rstrip()
        if not line or line.lstrip().startswith('#'):
            if not line.strip() and current is not None:
                entries.append(current)
                current = None
            continue
        if line.startswith('- '):
            if current is not None:
                entries.append(current)
            current = {}
            line = line[2:]
        else:
            line = line.lstrip()
        if ':' not in line:
            raise ValueError(f"{path}:{lineno}: malformed line: {raw!r}")
        key, _, value = line.partition(':')
        current[key.strip()] = _unquote(value.strip())
    if current is not None:
        entries.append(current)
    return entries


# ----- codegen -----

EMITTED_KINDS = {'function_pointer', 'address_constant'}


def pick_address(entry: dict, target: str) -> str:
    bg = entry.get('bg_addr', '').strip()
    if target == 'bg' and bg:
        return bg
    if target == 'auto' and bg:
        return bg
    return entry['original_addr']


def split_symbol(symbol: str) -> tuple:
    """Return (namespace_path_or_None, name)."""
    if '::' not in symbol:
        return (None, symbol)
    head, _, tail = symbol.rpartition('::')
    return (head, tail)


_IDENT = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')


def is_valid_cpp_ident(s: str) -> bool:
    return bool(_IDENT.match(s))


def is_valid_namespace_path(ns: str) -> bool:
    return all(is_valid_cpp_ident(part) for part in ns.split('::'))


def emit_header(entries: list, target: str, out_path: Path, source_yaml: Path) -> int:
    groups = defaultdict(list)  # namespace_path -> [(name, addr, entry)]
    skipped_invalid = 0

    for e in entries:
        if e.get('kind') not in EMITTED_KINDS:
            continue
        ns, name = split_symbol(e['symbol'])
        if not is_valid_cpp_ident(name):
            skipped_invalid += 1
            continue
        if ns is not None and not is_valid_namespace_path(ns):
            skipped_invalid += 1
            continue
        addr = pick_address(e, target)
        groups[ns or ''].append((name, addr, e))

    for ns in groups:
        groups[ns].sort(key=lambda t: t[0])

    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    relative_input = source_yaml.as_posix()

    lines = [
        '// =====================================================================',
        '// addresses_generated.h -- AUTO-GENERATED by tools/addresses/codegen.py',
        '// DO NOT EDIT BY HAND.',
        '//',
        f'// Source of truth: {relative_input}',
        f'// Target:          {target}',
        f'// Generated:       {now}',
        f'// Entries:         {sum(len(v) for v in groups.values())} of {len(entries)}',
        '//                  (only kind=function_pointer and address_constant are',
        '//                  emitted as named constants; nop_patch/data_read/',
        '//                  data_write remain inline at their call sites)',
        '//',
        '// Regenerate with:',
        '//     python3 tools/addresses/codegen.py',
        '// =====================================================================',
        '',
        '#pragma once',
        '',
        '#include <cstdint>',
        '',
        'namespace addresses',
        '{',
        '',
    ]

    if '' in groups:
        for name, addr, _e in groups['']:
            lines.append(f'constexpr std::uint32_t {name} = {addr};')
        lines.append('')

    for ns in sorted(k for k in groups if k):
        lines.append(f'namespace {ns}')
        lines.append('{')
        for name, addr, _e in groups[ns]:
            lines.append(f'    constexpr std::uint32_t {name} = {addr};')
        lines.append('}')
        lines.append('')

    lines.append('}  // namespace addresses')
    lines.append('')

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(lines), encoding='utf-8')

    return skipped_invalid


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().split('\n')[0])
    parser.add_argument('--input', type=Path,
                        default=Path('tools/addresses/addresses.yaml'))
    parser.add_argument('--output', type=Path,
                        default=Path('UtinniCore/generated/addresses_generated.h'))
    parser.add_argument('--target', choices=('auto', 'original', 'bg'),
                        default='auto',
                        help="auto = bg_addr if present else original_addr (default); "
                             "original = always original_addr; "
                             "bg = always bg_addr (errors if missing)")
    args = parser.parse_args()

    if not args.input.is_file():
        print(f"ERROR: {args.input} not found", file=sys.stderr)
        return 1

    entries = read_entries(args.input)

    if args.target == 'bg':
        missing = [e['symbol'] for e in entries
                   if e.get('kind') in EMITTED_KINDS and not e.get('bg_addr', '').strip()]
        if missing:
            print(f"ERROR: --target=bg requires bg_addr on every emitted entry; "
                  f"{len(missing)} entries are missing it.", file=sys.stderr)
            print(f"First few: {missing[:3]}", file=sys.stderr)
            return 1

    skipped = emit_header(entries, args.target, args.output, args.input)

    emitted_kinds = sum(1 for e in entries if e.get('kind') in EMITTED_KINDS)
    print(f"Read {len(entries)} entries from {args.input}")
    print(f"Emitted {emitted_kinds - skipped} named constants to {args.output}")
    print(f"  (skipped {skipped} entries with invalid C++ identifiers)")
    print(f"  (skipped {len(entries) - emitted_kinds} non-emitted-kind entries)")
    return 0


if __name__ == '__main__':
    sys.exit(main())
